[project]
name = "structured-outputs-demo"
version = "0.0.2"
description = "Local structured outputs"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "jsonschema>=4.24.0",
    "runpod>=1.7.12",
]
