name: Build and Push CUDA Image to Github Container Registry

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
    - '**.py'
    - 'Dockerfile'
    - '.github/workflows/build-cuda.yaml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: inference
jobs:
  cuda12_image_to_gcr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64, linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY }}/rubriclab/${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.REGISTRY }}/rubriclab/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}